[build]
  publish = "public"
  functions = "netlify/functions"
  command = "echo 'sem build - front-end estatico'"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"
